import { describe, expect, it } from "vitest";
import { adminActionNames } from "./registry";

const legacyAdminActionNames = [
  "overview",
  "listCampuses",
  "listCampusRequests",
  "approveCampusRequest",
  "rejectCampusRequest",
  "listPosts",
  "previewCommunityFeed",
  "getPost",
  "moderatePost",
  "bulkModeratePosts",
  "listPolls",
  "getPoll",
  "moderatePoll",
  "reviewPollDeletion",
  "listPostPins",
  "pinPost",
  "unpinPost",
  "listComments",
  "listModerationReports",
  "resolveModerationReport",
  "moderateComment",
  "bulkModerateComments",
  "listProfiles",
  "getProfile",
  "muteProfile",
  "unmuteProfile",
  "listFeedback",
  "updateFeedback",
  "listAnnouncements",
  "createAnnouncement",
  "updateAnnouncement",
  "listPostgraduateSources",
  "upsertPostgraduateSource",
  "setPostgraduateSourceStatus",
  "listPostgraduateSuggestions",
  "approvePostgraduateSuggestion",
  "rejectPostgraduateSuggestion",
  "listCatalogSuggestions",
  "approveCatalogSuggestion",
  "rejectCatalogSuggestion",
  "listTeachers",
  "upsertTeacher",
  "setTeacherStatus",
  "listCourses",
  "upsertCourse",
  "setCourseStatus",
  "listDishes",
  "upsertDish",
  "setDishStatus",
  "listTeacherRatings",
  "listDishRatings",
  "deleteTeacherRating",
  "deleteDishRating",
  "listSemesterRuntimeConfigs",
  "upsertSemesterRuntimeConfig",
  "listAdmins",
  "createAdmin",
  "updateAdmin",
  "disableAdmin",
  "listAuditLogs",
  "globalSearch",
  "listAdminSessions",
  "revokeAdminSession",
  "listNationalCalendarRuntimeConfigs",
  "upsertNationalCalendarRuntimeConfig"
] as const;

describe("admin action registry contract", () => {
  it("preserves every legacy action and registers the approved additions", () => {
    expect(adminActionNames).toEqual(legacyAdminActionNames);
  });
});
